engines:
  brakeman:
    enabled: true
  bundler-audit:
    enbaled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby:
        - javascript:
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
