dist: trusty
language: ruby
rvm:
  - 2.4.0
addons:
  apt:
    packages:
      - chromium-chromedriver
  code_climate:
    repo_token: 37eb546b3e87dacd5dd33885788fe45dda197ee6f7a018716564384ad8b9c2d6
  postgresql: "9.4"
services:
  - postgresql
before_install:
  - openssl aes-256-cbc -K $encrypted_af5caf69f7a8_key -iv $encrypted_af5caf69f7a8_iv -in config/deploy/id_rsa.enc -out config/deploy/id_rsa -d
before_script:
  - psql -c 'create database qwerty_master_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bin/rails db:migrate
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - bin/rails test
  - bin/rails test:system
after_success:
  - bundle exec codeclimate-test-reporter
  - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"
